require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/au10tixmobile/iOS_Artifacts_cocoapods_spec.git'

target 'Au10tixsdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Au10tixCore'

end
